project:
  type: website
  output-dir: _site
  

website:
  title: "I-ADOPT"
  site-url: "https://i-adopt.github.io/"
  repo-url: "https://github.com/i-adopt/i-adopt.github.io"
  repo-actions: [edit, issue]
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Ontology
        href: https://i-adopt.github.io/ontology/
      - text: Challenge
        href: challenge.qmd
  page-footer: 
    center: 
      - text: "About"
        href: about.qmd
      - text: "License: CC BY 4.0"
        href: https://creativecommons.org/licenses/by/4.0/


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    
execute:
  freeze: auto



